package com.cognizant.edgeservice.exception;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.web.reactive.error.ErrorWebExceptionHandler;
import org.springframework.core.annotation.Order;
import org.springframework.core.io.buffer.DataBuffer;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.server.reactive.ServerHttpResponse;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * Global reactive exception handler for the API Gateway.
 * Intercepts gateway-level errors (e.g. timeout, DNS resolution failure, connection refused, 404 routes)
 * and formats them into a production-ready structured JSON response.
 */
@Component
@Order(-2) // High precedence to handle exceptions before default WebFlux exception handlers
public class GlobalExceptionHandler implements ErrorWebExceptionHandler {

    private static final Logger LOGGER = LoggerFactory.getLogger(GlobalExceptionHandler.class);
    private final ObjectMapper objectMapper;

    // Injecting Jackson's ObjectMapper using constructor injection
    public GlobalExceptionHandler(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @Override
    public Mono<Void> handle(ServerWebExchange exchange, Throwable ex) {
        ServerHttpResponse response = exchange.getResponse();

        // 1. Prevent writing response if it is already committed
        if (response.isCommitted()) {
            return Mono.error(ex);
        }

        // 2. Set response header to JSON format
        response.getHeaders().setContentType(MediaType.APPLICATION_JSON);

        // 3. Determine HTTP Status and Message based on Exception type
        HttpStatus status = HttpStatus.INTERNAL_SERVER_ERROR;
        String message = "An unexpected gateway error occurred.";
        String errorType = ex.getClass().getSimpleName();

        if (ex instanceof ResponseStatusException) {
            ResponseStatusException rse = (ResponseStatusException) ex;
            status = HttpStatus.valueOf(rse.getStatusCode().value());
            message = rse.getReason();
        } else if (ex instanceof java.net.ConnectException || ex.getMessage() != null && ex.getMessage().toLowerCase().contains("connection refused")) {
            status = HttpStatus.SERVICE_UNAVAILABLE;
            message = "Downstream service is currently unavailable (Connection Refused).";
        } else if (ex instanceof io.netty.channel.ConnectTimeoutException || ex.getClass().getName().contains("TimeoutException")) {
            status = HttpStatus.GATEWAY_TIMEOUT;
            message = "Connection to downstream service timed out.";
        } else if (ex.getClass().getName().contains("NotFoundException") || ex.getClass().getName().contains("ResponseStatusException") && ex.getMessage().contains("404")) {
            status = HttpStatus.NOT_FOUND;
            message = "Requested route or downstream resource not found.";
        } else {
            // General fallback message
            message = ex.getMessage() != null ? ex.getMessage() : "Unknown gateway exception.";
        }

        response.setStatusCode(status);

        // 4. Build JSON Payload
        Map<String, Object> errorDetails = new HashMap<>();
        errorDetails.put("timestamp", LocalDateTime.now().toString());
        errorDetails.put("status", status.value());
        errorDetails.put("error", status.getReasonPhrase());
        errorDetails.put("message", message);
        errorDetails.put("path", exchange.getRequest().getPath().value());
        errorDetails.put("exceptionType", errorType);

        // Include request tracking ID if generated by RequestTrackingFilter, or generate one now for early-aborted requests (like 404)
        String trackingId = exchange.getAttribute("trackingId");
        if (trackingId == null) {
            trackingId = java.util.UUID.randomUUID().toString();
            exchange.getAttributes().put("trackingId", trackingId);
        }
        errorDetails.put("trackingId", trackingId);
        response.getHeaders().add("X-Request-Id", trackingId);

        // 5. Log the exception details using SLF4J
        LOGGER.error("[GATEWAY-ERROR] Exception: {}, Path: {}, Status: {}, Message: {}, TrackingID: {}",
                errorType, exchange.getRequest().getPath().value(), status.value(), message, trackingId, ex);

        // 6. Serialize JSON and write response buffer
        byte[] bytes;
        try {
            bytes = objectMapper.writeValueAsBytes(errorDetails);
        } catch (JsonProcessingException e) {
            LOGGER.error("Failed to serialize exception details", e);
            bytes = "{\"error\": \"Internal Server Error\"}".getBytes();
        }

        DataBuffer buffer = response.bufferFactory().wrap(bytes);
        return response.writeWith(Mono.just(buffer));
    }
}
